version: '3.7'
volumes:
  mongo_collector_db:
services:
  collector-db:
    image: mongo:4.2
    container_name: collector-db
    volumes:
    - mongo_collector_db:/data/db
#  test-db:
#    image: mongo:4.2
#    container_name: test-db
  profiler-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profiler-webapp
    volumes:
      - ./src/main/resources/config.prod.json:/usr/local/tomcat/config.json
    depends_on:
      - collector-db
#      - test-db
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "collector-db"
#     - "test-db"
